export type CallScope = "national" | "international";
export type CallStatus = "open" | "upcoming" | "archived";

export type FundingCall = {
  id: string;
  scope: CallScope;
  code: string;
  title: string;
  institution: string;
  institutionShort: string;
  status: CallStatus;
  openDate: string;
  deadline?: string;
  applicationType?: "fixed" | "continuous";
  preDeadline?: string;
  applicants: string;
  companyScale: string[];
  themes?: string[];
  sectors?: string[];
  fundingAmount: string;
  fundingType: string;
  supportRate?: string;
  duration?: string;
  summary: string;
  objectives: string[];
  eligibleCosts: string[];
  application: string;
  sourceUrl: string;
  sourceLabel: string;
  verifiedAt: string;
  tags: string[];
  featured?: boolean;
  notice?: string;
};

export const calls: FundingCall[] = [
  {
    id: "tubitak-1501-2026-2",
    scope: "national",
    code: "1501 · 2026/2",
    title: "Sanayi Ar-Ge Projeleri Destekleme Programı",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK",
    status: "open",
    openDate: "2026-07-20T00:00:00+03:00",
    deadline: "2026-10-26T23:59:00+03:00",
    preDeadline: "2026-10-22T17:30:00+03:00",
    applicants: "Türkiye’de yerleşik KOBİ ölçeğindeki sermaye şirketleri",
    companyScale: ["KOBİ"],
    fundingAmount: "Proje başına en fazla 20 milyon TL TÜBİTAK katkısı",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "İlk 5 proje için %75; 6. ve sonraki projeler için %60",
    duration: "En fazla 36 ay",
    summary:
      "KOBİ’lerin araştırma, teknoloji geliştirme ve yenilik faaliyetlerini proje esaslı olarak destekler. Konu sınırlaması bulunmayan çağrıda yenilikçi ürün ve süreç geliştirme çalışmaları hedeflenir.",
    objectives: [
      "Ar-Ge kapasitesini ve teknoloji geliştirme yetkinliğini artırmak",
      "Yeni veya iyileştirilmiş ürün ve süreçlerin ortaya çıkmasını sağlamak",
      "Ticarileşme potansiyeli yüksek projeleri desteklemek",
    ],
    eligibleCosts: [
      "Personel ve seyahat giderleri",
      "Alet, teçhizat, yazılım ve yayın giderleri",
      "Malzeme, danışmanlık ve Ar-Ge hizmet alımları",
    ],
    application: "Başvurular PRODİS üzerinden elektronik olarak yapılır.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/destekler/destek/sanayi/ulusal-destek-programlari/cagri-1501-sanayi-ar-ge-destek-programi-2026-yili-2-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK çağrı sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Ar-Ge", "Teknoloji", "Yenilik", "KOBİ"],
    themes: ["Ar-Ge ve Yenilik", "Ürün Geliştirme", "Dijital Dönüşüm", "Yeşil Dönüşüm"],
    sectors: ["İmalat", "Sektörler Arası"],
    featured: true,
    notice: "Kuruluş bazlı ön kayıt için son tarih 22 Ekim 2026’dır.",
  },
  {
    id: "tubitak-1507-2026-2",
    scope: "national",
    code: "1507 · 2026/2",
    title: "KOBİ Ar-Ge Başlangıç Destek Programı",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK",
    status: "open",
    openDate: "2026-07-20T00:00:00+03:00",
    deadline: "2026-11-11T23:59:00+03:00",
    preDeadline: "2026-11-09T17:30:00+03:00",
    applicants: "Ar-Ge projesi sunan Türkiye’de yerleşik KOBİ’ler",
    companyScale: ["KOBİ"],
    fundingAmount: "Çağrı dokümanındaki proje bütçesi ve üst limitler geçerlidir",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "Çağrı dokümanına göre belirlenir",
    duration: "Çağrı dokümanına göre belirlenir",
    summary:
      "Ar-Ge faaliyetine yeni başlayan KOBİ’lerin proje hazırlama ve yürütme yetkinliğini geliştirmeyi, yenilikçi ürün ve süreç fikirlerini sistematik Ar-Ge projelerine dönüştürmeyi amaçlar.",
    objectives: [
      "KOBİ’lerde Ar-Ge kültürünü yaygınlaştırmak",
      "İlk Ar-Ge projelerinin kurgulanmasını ve yürütülmesini kolaylaştırmak",
      "Teknolojik yeniliklerin pazara taşınmasını hızlandırmak",
    ],
    eligibleCosts: [
      "Personel ve proje seyahatleri",
      "Alet, teçhizat, yazılım ve malzeme",
      "Danışmanlık ve hizmet alımları",
    ],
    application: "Başvurular PRODİS üzerinden elektronik olarak yapılır.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/destekler/destek/sanayi/ulusal-destek-programlari/cagri-1507-kobi-ar-ge-baslangic-destek-programi-2026-yili-2-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK çağrı sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Ar-Ge", "Başlangıç", "KOBİ", "Yenilik"],
    themes: ["Ar-Ge ve Yenilik", "Ürün Geliştirme", "Girişimcilik"],
    sectors: ["İmalat", "Sektörler Arası"],
    featured: true,
    notice: "Kuruluş bazlı ön kayıt için son tarih 9 Kasım 2026’dır.",
  },
  {
    id: "tubitak-1711-2026",
    scope: "national",
    code: "1711 · YZE · 2026",
    title: "Yapay Zekâ Ekosistem Çağrısı",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK",
    status: "open",
    openDate: "2026-06-15T00:00:00+03:00",
    deadline: "2026-09-18T23:59:00+03:00",
    preDeadline: "2026-09-14T17:30:00+03:00",
    applicants:
      "Müşteri kuruluş, en az bir KOBİ teknoloji sağlayıcı ve üniversite/kamu araştırma birimi içeren konsorsiyumlar",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma"],
    fundingAmount: "Kuruluş türü ve çağrı dokümanındaki bütçe kurallarına göre",
    fundingType: "Hibe ve eş finansman",
    supportRate: "Kamu ve vakıf üniversitesi araştırma birimleri için %100; diğerleri çağrı koşullarına göre",
    duration: "Çağrı dokümanına göre belirlenir",
    summary:
      "Şirket ihtiyaçlarına yönelik yapay zekâ çözümlerinin, teknoloji sağlayıcı firmalar ve araştırma kurumlarıyla birlikte geliştirilmesini hedefleyen konsorsiyum çağrısıdır.",
    objectives: [
      "Yapay zekâ çözümlerini müşteri ihtiyaçlarına dönüştürmek",
      "Sanayi–üniversite iş birliğini güçlendirmek",
      "İklim, üretim, tarım, finans ve eğitim alanlarında uygulanabilir çözümler geliştirmek",
    ],
    eligibleCosts: [
      "Ar-Ge personeli ve proje faaliyetleri",
      "Yazılım, donanım, veri ve hizmet alımları",
      "Konsorsiyum kapsamında uygun görülen araştırma giderleri",
    ],
    application: "Konsorsiyum hazırlığı sonrasında başvuru PRODİS üzerinden yapılır.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/destekler/destek/sanayi/ulusal-destek-programlari/cagri-1711-yapay-zeka-ekosistem-2026-yili-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK çağrı sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Yapay Zekâ", "Sürdürülebilirlik", "Konsorsiyum"],
    themes: ["Dijital Dönüşüm", "Yapay Zekâ", "Ar-Ge ve Yenilik"],
    sectors: ["İmalat", "Finans", "Tarım ve Gıda", "Eğitim", "Sektörler Arası"],
    featured: true,
    notice: "Konsorsiyum kurulmadan yapılan başvurular değerlendirmeye alınmaz.",
  },
  {
    id: "horizon-hop-on-2026",
    scope: "international",
    code: "HORIZON-WIDERA-2026-03",
    title: "Hop-on Facility",
    institution: "European Research Executive Agency",
    institutionShort: "Horizon Europe",
    status: "open",
    openDate: "2026-01-13T09:00:00+01:00",
    deadline: "2026-09-24T17:00:00+02:00",
    applicants:
      "Widening ülkelerindeki araştırma kuruluşları; devam eden uygun Horizon Europe projelerine katılım için",
    companyScale: ["Üniversite / Araştırma", "KOBİ", "Büyük Ölçek"],
    fundingAmount: "Çağrı toplam bütçesi 30 milyon avro",
    fundingType: "Hibe",
    supportRate: "Horizon Europe uygun maliyet ve fonlama kurallarına göre",
    duration: "Katılım sağlanan projenin kalan süresine göre",
    summary:
      "Widening ülkelerindeki araştırma kuruluşlarının, uygun bir ortak içermeyen devam eden Horizon Europe Pillar 2 veya EIC Pathfinder projelerine katılmasını sağlar.",
    objectives: [
      "Araştırma ve yenilik kapasitesi düşük bölgelerin katılımını artırmak",
      "Devam eden Avrupa konsorsiyumlarını yeni yetkinliklerle güçlendirmek",
      "Avrupa Araştırma Alanı içindeki iş birliklerini genişletmek",
    ],
    eligibleCosts: [
      "Yeni ortağın proje faaliyetleri",
      "Personel, seyahat ve uygun araştırma giderleri",
      "Horizon Europe model hibe sözleşmesine uygun maliyetler",
    ],
    application: "Başvurular EU Funding & Tenders Portal üzerinden yapılır.",
    sourceUrl:
      "https://rea.ec.europa.eu/funding-and-grants/horizon-europe-widening-participation-and-spreading-excellence/hop-facility_en",
    sourceLabel: "Resmî Avrupa Komisyonu çağrı sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Horizon Europe", "Widening", "Ortaklık"],
    themes: ["Ar-Ge ve Yenilik", "Uluslararası İş Birliği"],
    sectors: ["Sektörler Arası"],
  },
  {
    id: "life-circular-2026",
    scope: "international",
    code: "LIFE-2026-SAP-ENV",
    title: "Döngüsel Ekonomi ve Sıfır Kirlilik – Standart Eylem Projeleri",
    institution: "European Climate, Infrastructure and Environment Executive Agency",
    institutionShort: "LIFE / CINEA",
    status: "open",
    openDate: "2026-04-21T09:00:00+02:00",
    deadline: "2026-09-22T17:00:00+02:00",
    applicants:
      "AB ve LIFE’a katılan ülkelerdeki kamu veya özel tüzel kişiler; tek başına ya da konsorsiyum olarak",
    companyScale: ["KOBİ", "Büyük Ölçek", "Kamu", "STK", "Üniversite / Araştırma"],
    fundingAmount: "Konu bazlı çağrı bütçesi ve proje katkısı Funding & Tenders Portal’da belirtilir",
    fundingType: "Eş finansmanlı hibe",
    supportRate: "Çağrı ve LIFE uygunluk kurallarına göre",
    duration: "Proje tasarımına ve çağrı koşullarına göre",
    summary:
      "Döngüsel ekonomi, kaynak verimliliği, sıfır kirlilik ve çevresel kalite alanlarında AB politika hedeflerine ölçülebilir katkı sağlayan uygulama projelerini destekler.",
    objectives: [
      "Döngüsel iş modellerini ve kaynak verimliliğini yaygınlaştırmak",
      "Atık, hava, su ve toprak kirliliğini azaltmak",
      "Çevre politikalarının uygulanmasını ve ölçeklenmesini desteklemek",
    ],
    eligibleCosts: [
      "Proje personeli ve uygulama faaliyetleri",
      "Ekipman amortismanı ve hizmet alımları",
      "Pilot uygulamalar, iletişim ve yaygınlaştırma giderleri",
    ],
    application: "Başvurular EU Funding & Tenders Portal üzerinden yapılır.",
    sourceUrl: "https://cinea.ec.europa.eu/life-calls-proposals-2026_en",
    sourceLabel: "Resmî CINEA LIFE 2026 sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Döngüsel Ekonomi", "Sıfır Kirlilik", "Yeşil Dönüşüm"],
    themes: ["Yeşil Dönüşüm", "Döngüsel Ekonomi", "Sıfır Kirlilik", "Kaynak Verimliliği"],
    sectors: ["İmalat", "Enerji", "Atık ve Geri Dönüşüm", "Su ve Çevre"],
    featured: true,
  },
  {
    id: "eic-accelerator-2026",
    scope: "international",
    code: "EIC Accelerator 2026",
    title: "EIC Accelerator Open",
    institution: "European Innovation Council",
    institutionShort: "EIC / Horizon",
    status: "open",
    openDate: "2026-01-01T09:00:00+01:00",
    deadline: "2026-09-02T17:00:00+02:00",
    applicants: "Yüksek büyüme potansiyeline sahip start-up ve KOBİ’ler; belirli koşullarda small mid-cap’ler",
    companyScale: ["Start-up", "KOBİ", "Small Mid-cap"],
    fundingAmount: "2,5 milyon avronun altında hibe ve 1–10 milyon avro yatırım bileşeni",
    fundingType: "Hibe, öz sermaye veya karma finansman",
    supportRate: "Program ve değerlendirme sonucuna göre",
    duration: "Hibe bileşeni faaliyetleri genellikle 24 aya kadar",
    summary:
      "TRL 6–8 seviyesindeki pazar yaratma veya mevcut pazarı dönüştürme potansiyeline sahip yüksek riskli yeniliklerin geliştirilmesini ve ölçeklenmesini destekler.",
    objectives: [
      "Çığır açıcı yenilikleri pazara taşımak",
      "Yüksek riskli ölçeklenme yatırımlarındaki finansman açığını kapatmak",
      "Avrupa’da küresel ölçekte rekabetçi teknoloji şirketleri oluşturmak",
    ],
    eligibleCosts: [
      "TRL 6–8 yenilik faaliyetleri",
      "Ürün doğrulama, demonstrasyon ve ölçekleme",
      "Hibe sözleşmesine uygun personel ve uygulama maliyetleri",
    ],
    application: "Kısa başvuru, tam başvuru ve jüri görüşmesi aşamaları Funding & Tenders Portal üzerinden yürütülür.",
    sourceUrl: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    sourceLabel: "Resmî EIC Accelerator sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Deep Tech", "Ölçeklenme", "Yatırım", "Hibe"],
    themes: ["Deep Tech", "Ölçeklenme", "Ar-Ge ve Yenilik"],
    sectors: ["Sektörler Arası"],
    notice: "2026 tam başvuru değerlendirme tarihleri içinde sıradaki kesim tarihi 2 Eylül 2026’dır.",
  },
  {
    id: "eic-step-scaleup-2026",
    scope: "international",
    code: "EIC STEP Scale Up 2026",
    title: "EIC STEP Scale Up",
    institution: "European Innovation Council",
    institutionShort: "EIC / STEP",
    status: "open",
    openDate: "2026-01-01T09:00:00+01:00",
    deadline: "2026-09-09T17:00:00+02:00",
    applicants: "Stratejik teknoloji alanlarında ölçeklenen start-up, KOBİ, spin-off ve small mid-cap’ler",
    companyScale: ["Start-up", "KOBİ", "Small Mid-cap"],
    fundingAmount: "10–30 milyon avro öz sermaye yatırımı",
    fundingType: "Doğrudan öz sermaye yatırımı",
    supportRate: "Yatırım değerlendirmesi ve ortak yatırım yapısına göre",
    duration: "Yatırım ve ölçeklenme planına göre",
    summary:
      "Kritik dijital, temiz ve biyoteknoloji alanlarındaki şirketlerin büyük özel yatırım turlarını katalize etmek üzere EIC Fund yatırımı sağlar.",
    objectives: [
      "Avrupa’nın stratejik teknoloji kapasitesini büyütmek",
      "Büyük ölçekli özel yatırımları harekete geçirmek",
      "Yüksek potansiyelli teknoloji şirketlerinin Avrupa’da ölçeklenmesini sağlamak",
    ],
    eligibleCosts: [
      "Ölçeklenme yatırımları",
      "Üretim ve pazara erişim kapasitesinin büyütülmesi",
      "Yatırım sözleşmesinde tanımlanan kullanım alanları",
    ],
    application: "Başvurular Funding & Tenders Portal üzerinden, EIC yatırım değerlendirme süreciyle yürütülür.",
    sourceUrl: "https://eic.ec.europa.eu/eic-funding-opportunities_en",
    sourceLabel: "Resmî EIC fonlama fırsatları sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["STEP", "Öz Sermaye", "Stratejik Teknoloji"],
    themes: ["Stratejik Yatırım", "Ölçeklenme", "Deep Tech"],
    sectors: ["Dijital Teknolojiler", "Temiz Teknolojiler", "Biyoteknoloji"],
  },
  {
    id: "eurostars-coordination-support-2026-2",
    scope: "national",
    code: "EUROSTARS-KOORD-DEST-2026-2",
    title: "Eurostars Koordinatörlük Desteği Programı 2026/2",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK / Eurostars",
    status: "open",
    openDate: "2026-06-05T00:00:00+03:00",
    deadline: "2026-07-27T23:59:00+03:00",
    preDeadline: "2026-07-23T23:59:00+03:00",
    applicants: "Eurostars 2026/2 çağrısına uluslararası proje koordinatörü olarak başvurmayı planlayan Türkiye’de yerleşik KOBİ’ler",
    companyScale: ["KOBİ"],
    fundingAmount: "Yurt içi uzman için 150.000 TL; yurt dışı uzman için 5.000 avro üst limit",
    fundingType: "Geri ödemesiz eğitim veya proje yazdırma desteği",
    supportRate: "%100",
    duration: "Eurostars 2026/2 başvuru hazırlık dönemi",
    summary:
      "Eurostars 2026/2 çağrısına koordinatör olarak hazırlanacak KOBİ’lerin proje yazma-sunma eğitimi ya da profesyonel proje yazdırma hizmeti giderlerini destekler.",
    objectives: [
      "Türkiye’deki KOBİ’lerin Eurostars konsorsiyumlarına liderlik etmesini artırmak",
      "Uluslararası proje önerilerinin niteliğini yükseltmek",
      "KOBİ’lerin yabancı ortaklarla güçlü Ar-Ge konsorsiyumları kurmasını kolaylaştırmak",
    ],
    eligibleCosts: [
      "Proje yazma ve sunma eğitimi bedeli",
      "Profesyonel proje yazdırma hizmeti",
      "Eğitim desteğinde en fazla iki ekip üyesinin uygun seyahat giderleri",
    ],
    application: "Kuruluş bazlı ön kayıt tamamlandıktan sonra başvuru TÜBİTAK PRODİS üzerinden yapılır.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/duyuru/eurostars-koordinatorluk-destegi-programi-2026-yili-2-ulusal-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK çağrı sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eurostars", "Koordinatörlük", "Proje Yazımı", "KOBİ"],
    themes: ["Uluslararası İş Birliği", "Ar-Ge ve Yenilik", "Proje Geliştirme"],
    sectors: ["Sektörler Arası"],
    featured: true,
    notice:
      "Yeni kuruluş bazlı ön kayıt süresi 23 Temmuz’da sona erdi. Daha önce ön kayıt onayı bulunan KOBİ’ler için başvuru son tarihi 27 Temmuz 2026’dır.",
  },
  {
    id: "eurostars-2026-2",
    scope: "international",
    code: "1709 · EUROSTARS · 2026/2",
    title: "Eurostars-3 2026 Yılı 2. Çağrısı",
    institution: "Eureka Sekretaryası ve TÜBİTAK",
    institutionShort: "Eurostars / TÜBİTAK",
    status: "open",
    openDate: "2026-07-09T12:00:00+02:00",
    deadline: "2026-09-10T14:00:00+02:00",
    preDeadline: "2026-09-21T23:59:00+03:00",
    applicants:
      "Yenilikçi bir KOBİ liderliğinde, en az iki Eurostars ülkesinden bağımsız kuruluşların oluşturduğu uluslararası konsorsiyumlar",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma", "Kamu"],
    fundingAmount:
      "Türk ortaklar için proje başına 600.000 avro; Türkiye’den ortaklı başvurularda toplam 850.000 avroya kadar",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "KOBİ %75, büyük ölçek %60, uygun araştırma/kamu kuruluşları %100",
    duration: "En fazla 36 ay",
    summary:
      "Konu sınırlaması olmadan, yenilikçi bir KOBİ liderliğinde kısa sürede ticarileşebilecek ürün, süreç veya hizmet geliştiren uluslararası Ar-Ge ve yenilik projelerini destekler.",
    objectives: [
      "Yenilikçi KOBİ’lerin uluslararası Ar-Ge kapasitesini artırmak",
      "Pazara yakın ürün, süreç ve hizmetleri birlikte geliştirmek",
      "KOBİ’lerin küresel değer zincirlerine ve yeni pazarlara erişimini kolaylaştırmak",
    ],
    eligibleCosts: [
      "Personel ve seyahat giderleri",
      "Alet, teçhizat, yazılım, yayın ve malzeme giderleri",
      "Danışmanlık ve uygun hizmet alımları",
    ],
    application:
      "Uluslararası başvuru Eureka proje platformuna yapılır; Türkiye’deki ortaklar ayrıca PRODİS üzerinden ulusal ön proje başvurusunu tamamlar.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/duyuru/1709-eureka-eurostars-2026-yili-2-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK Eurostars 2026/2 çağrı sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eurostars", "Uluslararası Ar-Ge", "KOBİ", "Konsorsiyum"],
    themes: ["Uluslararası İş Birliği", "Ar-Ge ve Yenilik", "Ürün Geliştirme"],
    sectors: ["Sektörler Arası"],
    featured: true,
    notice:
      "Uluslararası son tarih 10 Eylül; kuruluş bazlı ön kayıt 21 Eylül, ulusal ön proje başvurusu 24 Eylül 2026’dır.",
  },
  {
    id: "eureka-biotech-2026",
    scope: "international",
    code: "1719 · EUREKA BİYOTEKNOLOJİ",
    title: "Eureka Network Biyoteknoloji 2026 Çağrısı",
    institution: "Eureka Network ve TÜBİTAK",
    institutionShort: "Eureka / TÜBİTAK",
    status: "open",
    openDate: "2026-03-31T00:00:00+02:00",
    deadline: "2026-09-25T14:00:00Z",
    preDeadline: "2026-11-17T23:59:00+03:00",
    applicants:
      "En az iki katılımcı Eureka ülkesinden bağımsız kuruluşlar; Türkiye’de sermaye şirketi yürütücülüğünde üniversite ve araştırma kuruluşları ortak olabilir",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma", "Kamu"],
    fundingAmount: "Türk ortakların proje bütçesi en fazla 500.000 avro; ulusal çağrı bütçesi 2,5 milyon avro",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "KOBİ %75, büyük ölçek %60, uygun araştırma/kamu kuruluşları %100",
    duration: "En fazla 36 ay",
    summary:
      "İleri biyolojik üretim, yeni nesil tedaviler, tarım ve veterinerlik biyoteknolojisi ile ileri tanı ve veri teknolojilerinde pazara yönelik uluslararası Ar-Ge projelerini destekler.",
    objectives: [
      "Biyoteknoloji alanında uluslararası Ar-Ge iş birliklerini güçlendirmek",
      "Ticarileşme potansiyeli yüksek ürün, süreç ve hizmetler geliştirmek",
      "Biyolojik üretim, tarım, tanı ve veri teknolojilerinde yeniliği hızlandırmak",
    ],
    eligibleCosts: [
      "Personel ve seyahat giderleri",
      "Alet, teçhizat, yazılım, yayın ve malzeme giderleri",
      "Danışmanlık ve uygun hizmet alımları",
    ],
    application:
      "Uluslararası Eureka formu çevrim içi sunulur; olumlu uluslararası değerlendirme sonrasında Türkiye ortakları PRODİS üzerinden ulusal başvuru yapar.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/duyuru/1719-eureka-network-biyoteknoloji-2026-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK 1719 Biyoteknoloji çağrı sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eureka", "Biyoteknoloji", "Tarım", "Tanı"],
    themes: ["Ar-Ge ve Yenilik", "Biyoteknoloji", "Uluslararası İş Birliği"],
    sectors: ["Biyoteknoloji", "Sağlık", "Tarım ve Gıda"],
    featured: true,
    notice:
      "TÜBİTAK duyurusuna göre uluslararası son tarih 25 Eylül saat 14.00 GMT’dir; kuruluş bazlı ön kayıt 17 Kasım, ulusal proje başvurusu 18 Kasım 2026’dır.",
  },
  {
    id: "eureka-lightweighting-2026",
    scope: "international",
    code: "1719 · EUREKA HAFİFLETME",
    title: "Eureka Network Hafifletme Teknolojileri 2026",
    institution: "Eureka Network ve TÜBİTAK",
    institutionShort: "Eureka / TÜBİTAK",
    status: "open",
    openDate: "2026-05-06T00:00:00+02:00",
    deadline: "2026-10-08T14:00:00Z",
    preDeadline: "2026-12-01T23:59:00+03:00",
    applicants:
      "En az iki katılımcı ülkeden uluslararası konsorsiyumlar; Türkiye’de sermaye şirketi yürütücülüğünde üniversite ve araştırma kuruluşları ortak olabilir",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma", "Kamu"],
    fundingAmount: "Türk ortakların proje bütçesi en fazla 500.000 avro; ulusal çağrı bütçesi 2,5 milyon avro",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "KOBİ %75, büyük ölçek %60, uygun araştırma/kamu kuruluşları %100",
    duration: "En fazla 36 ay",
    summary:
      "Kaynak verimliliği, emisyon azaltımı ve döngüsel ekonomi hedefleri doğrultusunda hafif malzeme, ürün tasarımı, üretim ve dijitalleşme çözümlerini destekler.",
    objectives: [
      "Ürün ve sistemlerde ağırlığı ve kaynak tüketimini azaltmak",
      "Yeniden kullanılabilir ve geri dönüştürülebilir tasarımları geliştirmek",
      "Hafifletme teknolojilerini pazara yakın uluslararası projelere dönüştürmek",
    ],
    eligibleCosts: [
      "Personel ve seyahat giderleri",
      "Alet, teçhizat, yazılım ve malzeme giderleri",
      "Danışmanlık ve uygun hizmet alımları",
    ],
    application:
      "Uluslararası başvuru Eureka platformuna yapılır; Türkiye ortakları çağrı takvimine göre PRODİS üzerinden ulusal başvuru yapar.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/duyuru/eureka-network-hafifletme-teknolojileri-2026-yili-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK 1719 Hafifletme Teknolojileri sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eureka", "Hafifletme", "Döngüsel Ekonomi", "Emisyon"],
    themes: ["Yeşil Dönüşüm", "Döngüsel Ekonomi", "Ar-Ge ve Yenilik"],
    sectors: ["Otomotiv ve Mobilite", "Havacılık ve Uzay", "İmalat", "Malzeme"],
    featured: true,
    notice:
      "TÜBİTAK duyurusuna göre uluslararası son tarih 8 Ekim saat 14.00 UTC’dir; kuruluş bazlı ön kayıt 1 Aralık, ulusal proje başvurusu 2 Aralık 2026’dır.",
  },
  {
    id: "eureka-disaster-resilience-2026",
    scope: "international",
    code: "1719 · EUREKA AFET DİRENÇLİLİĞİ",
    title: "Eureka Network Afetlerde Dirençlilik 2026",
    institution: "Eureka Network ve TÜBİTAK",
    institutionShort: "Eureka / TÜBİTAK",
    status: "open",
    openDate: "2026-06-08T00:00:00+02:00",
    deadline: "2026-10-26T14:00:00+02:00",
    preDeadline: "2026-12-15T23:59:00+03:00",
    applicants:
      "En az iki katılımcı Eureka ülkesinden bağımsız kuruluşlar; Türkiye’de sermaye şirketi yürütücülüğünde araştırma kuruluşları ortak olabilir",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma", "Kamu"],
    fundingAmount: "Türk ortakların proje bütçesi en fazla 500.000 avro; ulusal çağrı bütçesi 2,5 milyon avro",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "KOBİ %75, büyük ölçek %60, uygun araştırma/kamu kuruluşları %100",
    duration: "En fazla 36 ay",
    summary:
      "Doğal ve insan kaynaklı afetlere hazırlık, müdahale ve iyileştirme için THS 5 ve üzerindeki pazara yakın teknoloji, ürün, hizmet ve süreçleri destekler.",
    objectives: [
      "Afetlere hazırlık ve erken uyarı kapasitesini güçlendirmek",
      "Müdahale ve arama-kurtarma teknolojilerini geliştirmek",
      "Döngüsel ve dirençli afet sonrası iyileştirme çözümleri oluşturmak",
    ],
    eligibleCosts: [
      "Personel ve seyahat giderleri",
      "Alet, teçhizat, yazılım ve malzeme giderleri",
      "Danışmanlık ve uygun hizmet alımları",
    ],
    application:
      "Uluslararası Eureka başvurusu çevrim içi sunulur; Türkiye ortakları olumlu değerlendirme sonrasında PRODİS üzerinden ulusal başvuru yapar.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/duyuru/eureka-network-afetlerde-direnclilik-2026-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK 1719 Afetlerde Dirençlilik sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eureka", "Afet Dirençliliği", "Yapay Zekâ", "Döngüsellik"],
    themes: ["Afet Dirençliliği", "Dijital Dönüşüm", "Yeşil Dönüşüm", "Uluslararası İş Birliği"],
    sectors: ["Yapı ve İnşaat", "Dijital Teknolojiler", "Su ve Çevre", "Enerji"],
    notice:
      "TÜBİTAK duyurusuna göre uluslararası son tarih 26 Ekim saat 14.00 CEST’tir; kuruluş bazlı ön kayıt 15 Aralık, ulusal proje başvurusu 16 Aralık 2026’dır.",
  },
  {
    id: "eureka-xecs-quantum-2026",
    scope: "international",
    code: "1719 · XECS KUANTUM · 2026",
    title: "Eureka Xecs Uygulamalı Kuantum Teknolojileri",
    institution: "Eureka Xecs Kümesi ve TÜBİTAK",
    institutionShort: "Xecs / TÜBİTAK",
    status: "open",
    openDate: "2026-06-23T12:00:00+02:00",
    deadline: "2026-11-26T17:00:00+01:00",
    applicants:
      "En az iki destekleyen Eureka ülkesinden kuruluşların oluşturduğu konsorsiyumlar; Türkiye’de sermaye şirketi yürütücü olmalıdır",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma", "Kamu"],
    fundingAmount: "Türk ortakların toplam proje bütçesi en fazla 600.000 avro",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "Ulusal çağrı kuralları ve kuruluş türüne göre",
    duration: "En fazla 36 ay",
    summary:
      "Kuantum algılama, metroloji, haberleşme, siber güvenlik ve kuantum hesaplama için etkinleştirici elektronik bileşen ve sistemlerde uygulamalı Ar-Ge projelerini destekler.",
    objectives: [
      "Uygulamalı kuantum teknolojilerini THS 6–7 seviyelerine taşımak",
      "Uluslararası bilgi ve teknoloji transferini güçlendirmek",
      "Türkiye’de özgün kuantum bileşenleri ve sistemleri geliştirmek",
    ],
    eligibleCosts: [
      "Ar-Ge personeli ve proje seyahatleri",
      "Donanım, yazılım, prototip ve malzeme giderleri",
      "Ulusal çağrı kurallarına uygun araştırma ve hizmet giderleri",
    ],
    application:
      "İlk aşamada Xecs Project Outline sunulur; davet edilen projeler tam öneri ve ardından TÜBİTAK PRODİS ulusal başvurusu yapar.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/duyuru/eureka-xecs-2026-uygulamali-kuantum-teknolojileri-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK Xecs Kuantum çağrı sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eureka", "Xecs", "Kuantum", "Elektronik"],
    themes: ["Kuantum Teknolojileri", "Dijital Dönüşüm", "Ar-Ge ve Yenilik"],
    sectors: ["Elektronik", "Dijital Teknolojiler", "Savunma ve Güvenlik"],
    notice:
      "26 Kasım 2026 Project Outline son tarihidir. Tam proje 5 Mart, ulusal PRODİS başvurusu 31 Mart 2027’de kapanır.",
  },
  {
    id: "eureka-xecs-call-6-2026",
    scope: "international",
    code: "1509 · XECS CALL 6",
    title: "Eureka Xecs 6. Çağrısı",
    institution: "Eureka Xecs Kümesi ve TÜBİTAK",
    institutionShort: "Xecs / TÜBİTAK",
    status: "open",
    openDate: "2026-06-02T00:00:00+02:00",
    deadline: "2027-01-21T17:00:00+01:00",
    applicants:
      "Elektronik bileşenler ve sistemler alanında uluslararası konsorsiyumlar; Türkiye’den doğrudan ortak olarak sermaye şirketleri",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    fundingAmount: "Türk katılımcılar için 1509 programı ve ulusal değerlendirme kurallarına göre",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "KOBİ %75’e, büyük ölçekli şirketler %60’a kadar",
    duration: "Çağrı ve 1509 programı kurallarına göre",
    summary:
      "Mikro/nanoelektronik, akıllı sistem entegrasyonu, gömülü ve siber-fiziksel sistemler ile sistemler sistemi alanlarında uluslararası Ar-Ge projelerini destekler.",
    objectives: [
      "Sürdürülebilir dijital dönüşümü hızlandırmak",
      "Elektronik bileşenler ve sistemler değer zincirini güçlendirmek",
      "Pazara yakın uluslararası endüstriyel Ar-Ge projeleri geliştirmek",
    ],
    eligibleCosts: [
      "Personel ve seyahat giderleri",
      "Alet, teçhizat, yazılım ve malzeme giderleri",
      "1509 programı kapsamında uygun hizmet ve danışmanlık giderleri",
    ],
    application:
      "Xecs platformunda Project Outline ve ardından Full Project Proposal sunulur; Türkiye’deki firmalar ulusal aşamada TÜBİTAK’a başvurur.",
    sourceUrl: "https://tubitak.gov.tr/tr/duyuru/eureka-xecs-6-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK Xecs 6 çağrı sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eureka", "Xecs", "Elektronik", "Dijital Dönüşüm"],
    themes: ["Dijital Dönüşüm", "Ar-Ge ve Yenilik", "Uluslararası İş Birliği"],
    sectors: ["Elektronik", "Dijital Teknolojiler", "Otomotiv ve Mobilite", "İmalat"],
    notice: "Project Outline son tarihi 21 Ocak, Full Project Proposal son tarihi 5 Nisan 2027’dir.",
  },
  {
    id: "eureka-smart-call-10-2026",
    scope: "international",
    code: "1509 · SMART CALL 10",
    title: "Eureka SMART Kümesi 10. Çağrısı",
    institution: "Eureka SMART Kümesi ve TÜBİTAK",
    institutionShort: "SMART / TÜBİTAK",
    status: "open",
    openDate: "2026-07-01T00:00:00+02:00",
    deadline: "2027-01-26T11:00:00+01:00",
    applicants:
      "İleri imalat alanında uluslararası, sanayi odaklı Ar-Ge konsorsiyumları; Türkiye’den sermaye şirketleri",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    fundingAmount: "Türk katılımcılar için 1509 programı ve ulusal değerlendirme kurallarına göre",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "1509 programı ve kuruluş ölçeğine göre",
    duration: "Çağrı ve 1509 programı kurallarına göre",
    summary:
      "İleri imalatta rekabetçi ve sürdürülebilir çözümler geliştiren, pazara yakın ve uluslararası iş birlikli Ar-Ge ve yenilik projelerini destekler.",
    objectives: [
      "Sürdürülebilir ileri imalat teknolojilerini geliştirmek",
      "Uluslararası sanayi ve araştırma iş birliklerini güçlendirmek",
      "İmalat sektöründe dijital ve yeşil dönüşümü hızlandırmak",
    ],
    eligibleCosts: [
      "Ar-Ge personeli ve proje seyahatleri",
      "Alet, teçhizat, yazılım ve malzeme giderleri",
      "1509 programına uygun danışmanlık ve hizmet alımları",
    ],
    application:
      "İlk aşamada SMART Project Outline sunulur; davet edilen konsorsiyumlar Full Project Proposal ve ulusal başvuru süreçlerini tamamlar.",
    sourceUrl: "https://tubitak.gov.tr/tr/duyuru/eureka-smart-kumesi-10-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK SMART 10 çağrı sayfası",
    verifiedAt: "2026-07-26T12:00:00+03:00",
    tags: ["Eureka", "SMART", "İleri İmalat", "Yeşil Dönüşüm"],
    themes: ["İleri İmalat", "Dijital Dönüşüm", "Yeşil Dönüşüm", "Uluslararası İş Birliği"],
    sectors: ["İmalat", "Makine", "Otomasyon ve Robotik"],
    notice: "Project Outline son tarihi 26 Ocak, Full Project Proposal son tarihi 15 Nisan 2027’dir.",
  },
  {
    id: "tubitak-1831-continuous",
    scope: "national",
    code: "1831 · Yeşil Mentörlük",
    title: "Yeşil İnovasyon Teknoloji Mentörlük Çağrısı",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK",
    status: "open",
    openDate: "2024-05-16T00:00:00+03:00",
    deadline: "2030-01-01T23:59:00+03:00",
    applicants: "Sermaye şirketi niteliğindeki KOBİ’ler",
    companyScale: ["KOBİ"],
    themes: ["Yeşil Dönüşüm", "Karbon Yönetimi", "Kaynak Verimliliği", "Mentörlük"],
    sectors: ["İmalat", "Sektörler Arası"],
    fundingAmount: "Proje bütçesi üst limiti 310.000 TL",
    fundingType: "Geri ödemesiz hibe",
    supportRate: "Uzman kuruluş hizmet bedelinin %90’ı",
    duration: "3–6 ay",
    summary:
      "KOBİ’lerin yeşil dönüşüm mevzuatına uyum, mevcut durum ve kapasite analizi, teknoloji danışmanlığı ve yol haritası hazırlama hizmetlerini destekler.",
    objectives: [
      "KOBİ’nin yeşil dönüşüm olgunluğunu belirlemek",
      "Mevzuat, emisyon ve kaynak verimliliği ihtiyaçlarını analiz etmek",
      "Uygulanabilir bir yeşil dönüşüm yol haritası oluşturmak",
    ],
    eligibleCosts: [
      "Onaylı çözüm ortağından mentörlük ve danışmanlık hizmeti",
      "Mevcut durum ve kapasite analizi",
      "Yeşil dönüşüm yol haritası hazırlanması",
    ],
    application: "Başvuru, TÜBİTAK’ın ilan ettiği çözüm ortaklarıyla birlikte PRODİS üzerinden yürütülür.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/destekler/sanayi/ulusal-destek-programlari/1831-yesil-inovasyon-teknoloji-mentorluk-cagrisi",
    sourceLabel: "Resmî TÜBİTAK 1831 program sayfası",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["Yeşil Dönüşüm", "Mentörlük", "KOBİ", "Yol Haritası"],
    featured: true,
    notice: "TÜBİTAK açık çağrılar sayfasında başvuru bitişi 1 Ocak 2030 olarak gösterilmektedir.",
  },
  {
    id: "sanayi-yesil-donusum-programi-2026",
    scope: "national",
    code: "YDP · 2026",
    title: "Sanayi ve Teknoloji Bakanlığı Yeşil Dönüşüm Programı",
    institution: "T.C. Sanayi ve Teknoloji Bakanlığı",
    institutionShort: "Sanayi Bakanlığı",
    status: "open",
    openDate: "2026-06-23T00:00:00+03:00",
    deadline: "2026-07-31T23:59:00+03:00",
    applicants: "Döngüsel ekonomi ve düşük karbonlu üretime yönelik yatırım planlayan sanayi işletmeleri",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    themes: ["Yeşil Dönüşüm", "Döngüsel Ekonomi", "Düşük Karbon", "Kaynak Verimliliği"],
    sectors: ["İmalat", "Enerji", "Atık ve Geri Dönüşüm", "Su ve Çevre"],
    fundingAmount: "Proje bazında uygun yatırım teşvik unsurları",
    fundingType: "Yatırım teşviki ve proje bazlı destek",
    supportRate: "Yatırımın niteliği ve teşvik belgesine göre",
    duration: "Yol haritası ve yatırım planına göre",
    summary:
      "Sanayide döngüsel ekonomi, kaynak verimliliği ve düşük karbonlu üretim yatırımlarının yeşil dönüşüm yol haritası temelinde desteklenmesini amaçlar.",
    objectives: [
      "Sanayi tesislerinin karbon ve kaynak yoğunluğunu azaltmak",
      "Döngüsel üretim modellerini yaygınlaştırmak",
      "Yeşil teknoloji yatırımlarını hızlandırmak",
    ],
    eligibleCosts: [
      "Çağrı ve yatırım teşvik mevzuatında uygun görülen yatırım kalemleri",
      "Enerji ve kaynak verimli üretim teknolojileri",
      "Düşük karbonlu ve döngüsel üretim yatırımları",
    ],
    application: "Başvuru ve yol haritası işlemleri Yeşil Dönüşüm Programı portalı üzerinden yapılır.",
    sourceUrl: "https://ticaret.gov.tr/dis-iliskiler/yesil-mutabakat/duyurular/yesil-donusum-programi-cagri-duyurusu",
    sourceLabel: "Resmî Bakanlık Yeşil Dönüşüm Programı duyurusu",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["Sanayi Bakanlığı", "Yeşil Dönüşüm", "Yatırım", "Düşük Karbon"],
    featured: true,
    notice: "Resmî duyuruda son başvuru tarihi 31 Temmuz 2026 olarak ilan edilmiştir.",
  },
  {
    id: "ticaret-responsible-programi",
    scope: "national",
    code: "Responsible®",
    title: "Yeşil Mutabakata Uyum Projesi Desteği",
    institution: "T.C. Ticaret Bakanlığı",
    institutionShort: "Ticaret Bakanlığı",
    status: "open",
    openDate: "2024-06-26T00:00:00+03:00",
    applicationType: "continuous",
    applicants: "İhracat yapan veya ihracat hedefi bulunan, program koşullarını sağlayan şirketler",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    themes: ["Yeşil Dönüşüm", "İhracat", "Sürdürülebilirlik", "Dijital Dönüşüm"],
    sectors: ["İmalat", "İhracat", "Sektörler Arası"],
    fundingAmount: "2026 yılı danışmanlık gideri üst limiti 17.640.256 TL",
    fundingType: "Geri ödemesiz danışmanlık desteği",
    supportRate: "5973 sayılı Karar ve güncel genelgeye göre",
    duration: "Faz 1–3 program sürecine göre",
    summary:
      "Şirketlerin yeşil ve dijital dönüşüm mevcut durum analizi, sürdürülebilirlik yol haritası, uygulama danışmanlığı ve doğrulama ihtiyaçlarını Responsible® çerçevesinde destekler.",
    objectives: [
      "İhracatçıların Yeşil Mutabakat ve sürdürülebilirlik gerekliliklerine uyumunu artırmak",
      "Kurumsal dönüşüm yol haritası oluşturmak",
      "Uluslararası pazarlarda rekabetçiliği korumak",
    ],
    eligibleCosts: [
      "Mevcut durum analizi ve sürdürülebilirlik yol haritası",
      "Program kapsamındaki teknik ve yönetim danışmanlıkları",
      "Doğrulama ve sürdürülebilirlik uygulamaları",
    ],
    application: "Başvurular Responsible® Portalı ve Destek Yönetim Sistemi üzerinden yürütülür.",
    sourceUrl:
      "https://ticaret.gov.tr/destekler/ihracat-destekleri/5973-sayili-ihracat-destekleri-hakkinda-karara-iliskin-genelgeler/yesil-mutabakata-uyum-projesi-destegi-responsible-programi",
    sourceLabel: "Resmî Ticaret Bakanlığı Responsible® sayfası",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["Responsible", "Yeşil Mutabakat", "İhracat", "Danışmanlık"],
    featured: true,
  },
  {
    id: "ticaret-pazara-giris-belgesi",
    scope: "national",
    code: "5973 · Madde 3",
    title: "Pazara Giriş Belgesi Desteği",
    institution: "T.C. Ticaret Bakanlığı",
    institutionShort: "Ticaret Bakanlığı",
    status: "open",
    openDate: "2022-08-18T00:00:00+03:00",
    applicationType: "continuous",
    applicants: "İhracat yapan veya ihracata hazırlanan, mevzuattaki şirket koşullarını sağlayan işletmeler",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    themes: ["İhracat", "Belgelendirme", "Pazara Giriş", "Uygunluk"],
    sectors: ["İmalat", "İhracat", "Tarım ve Gıda", "Sağlık", "Sektörler Arası"],
    fundingAmount: "2026 yılı üst limiti 19.728.672 TL",
    fundingType: "Geri ödemesiz gider desteği",
    supportRate: "5973 sayılı Karar ve güncel genelgeye göre",
    duration: "Belge ve harcama başvurusu dönemine göre",
    summary:
      "Şirketlerin hedef pazarlara girişte ihtiyaç duyduğu kalite, çevre, güvenlik ve uygunluk belgeleri ile ruhsatlandırma ve kayıt giderlerini destekler.",
    objectives: [
      "Ürünlerin dış pazarlara teknik ve mevzuatsal erişimini kolaylaştırmak",
      "Uluslararası belge ve sertifikasyon maliyetlerini azaltmak",
      "İhracat kapasitesini ve ürün güvenilirliğini artırmak",
    ],
    eligibleCosts: [
      "Desteklenen pazara giriş belgeleri",
      "Ruhsatlandırma ve kayıt işlemleri",
      "Genelgede uygun görülen test, analiz ve belgelendirme giderleri",
    ],
    application: "Başvuru, ilgili ihracatçı birliği ve Destek Yönetim Sistemi üzerinden yapılır.",
    sourceUrl:
      "https://ticaret.gov.tr/destekler/ihracat-destekleri/5973-sayili-ihracat-destekleri-hakkinda-karara-iliskin-genelgeler/pazara-giris-belgesi-destegi",
    sourceLabel: "Resmî Ticaret Bakanlığı Pazara Giriş Belgesi sayfası",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["İhracat", "Belgelendirme", "Sertifikasyon", "Pazara Giriş"],
  },
  {
    id: "kosgeb-kobi-dijital-donusum",
    scope: "national",
    code: "KOBİ Dijital Dönüşüm",
    title: "KOBİ Dijital Dönüşüm Destek Programı",
    institution: "Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi",
    institutionShort: "KOSGEB",
    status: "open",
    openDate: "2024-05-21T00:00:00+03:00",
    applicationType: "continuous",
    applicants: "Onaylı dijital olgunluk raporu bulunan küçük ve orta ölçekli imalat işletmeleri",
    companyScale: ["KOBİ"],
    themes: ["Dijital Dönüşüm", "Verimlilik", "Otomasyon", "Akıllı Üretim"],
    sectors: ["İmalat", "Makine", "Otomasyon ve Robotik", "Dijital Teknolojiler"],
    fundingAmount: "1–20 milyon TL yatırım kredisi",
    fundingType: "Kredi faiz desteği",
    supportRate: "20 puan geri ödemesiz finansman desteği",
    duration: "24 ay program; azami 36 ay kredi vadesi",
    summary:
      "İmalat KOBİ’lerinin onaylı dijital olgunluk raporundaki yol haritasına uygun makine, teçhizat, yazılım ve donanım yatırımlarını destekler.",
    objectives: [
      "Üretim süreçlerini dijitalleştirmek ve verimliliği artırmak",
      "Akıllı üretim ve veri temelli yönetim kapasitesi oluşturmak",
      "KOBİ’lerin rekabet gücünü yükseltmek",
    ],
    eligibleCosts: [
      "Yeni makine ve teçhizat",
      "Yazılım ve donanım",
      "Onaylı dijital dönüşüm planındaki uygun yatırımlar",
    ],
    application: "Önce yetkili danışmandan DDX veya SIRI raporu alınır; ardından KOSGEB KOBİ Bilgi Sistemi üzerinden başvurulur.",
    sourceUrl: "https://www.kosgeb.gov.tr/site/tr/genel/detay/9144/kobi-dijital-donusum-destek-programi",
    sourceLabel: "Resmî KOSGEB KOBİ Dijital Dönüşüm sayfası",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["KOSGEB", "Dijital Dönüşüm", "İmalat", "Kredi"],
    featured: true,
  },
  {
    id: "kosgeb-yapay-zeka-kredi-2026",
    scope: "national",
    code: "GO Dijital · YZ 2026",
    title: "Yapay Zekâ Kredi Programı",
    institution: "KOSGEB ve GO Dijital Cüzdan",
    institutionShort: "KOSGEB",
    status: "open",
    openDate: "2026-07-09T00:00:00+03:00",
    deadline: "2026-12-31T23:59:00+03:00",
    applicants: "Geçerli Teknogirişim Rozetine sahip, KOSGEB veri tabanında aktif işletmeler",
    companyScale: ["Start-up", "KOBİ"],
    themes: ["Dijital Dönüşüm", "Yapay Zekâ", "Bulut ve Veri", "Girişimcilik"],
    sectors: ["Dijital Teknolojiler", "Yazılım", "Veri Merkezi", "Sektörler Arası"],
    fundingAmount: "500 bin–5 milyon TL kredi",
    fundingType: "Geri ödemeli kredi",
    supportRate: "12 ay geri ödemesiz dönem, ardından 12 ay eşit taksit",
    duration: "24 aylık geri ödeme yapısı",
    summary:
      "Teknogirişimlerin GPU/CPU/RAM, güvenli veri saklama, yapay zekâ veri merkezi ve platform hizmetlerine erişimini finanse eder.",
    objectives: [
      "Yapay zekâ geliştirme ve uygulama kapasitesini artırmak",
      "Yüksek performanslı hesaplama altyapısına erişimi kolaylaştırmak",
      "Teknoloji girişimlerinin rekabetçiliğini güçlendirmek",
    ],
    eligibleCosts: [
      "GPU, CPU ve RAM işlem kaynakları",
      "Güvenli veri depolama ve veri merkezi hizmetleri",
      "Yapay zekâ araçları ve platform hizmetleri",
    ],
    application: "Başvurular KOSGEB KOBİ Bilgi Sistemi üzerinden alınır; kredi kullanımı GO Dijital Cüzdan üzerinden yürütülür.",
    sourceUrl: "https://www.kosgeb.gov.tr/site/tr/genel/detay/9427/kosgebden-teknoloji-girisimlerine-yapay-zek-kredi-programi",
    sourceLabel: "Resmî KOSGEB Yapay Zekâ Kredi Programı duyurusu",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["Yapay Zekâ", "Teknogirişim", "GPU", "Kredi"],
    featured: true,
  },
  {
    id: "sanayi-hit30-active",
    scope: "national",
    code: "HIT-30 · Aktif Çağrılar",
    title: "HIT-30 Yüksek Teknoloji Yatırım Çağrıları",
    institution: "T.C. Sanayi ve Teknoloji Bakanlığı",
    institutionShort: "HIT-30",
    status: "open",
    openDate: "2026-07-26T00:00:00+03:00",
    applicationType: "continuous",
    applicants: "Teknik ve mali yeterliliğe sahip yerli veya uluslararası yatırımcı şirketler",
    companyScale: ["Büyük Ölçek", "KOBİ", "Yatırımcı"],
    themes: ["Stratejik Yatırım", "Dijital Dönüşüm", "Yeşil Dönüşüm", "İleri İmalat"],
    sectors: ["Savunma ve Güvenlik", "Otomotiv ve Mobilite", "Enerji", "Yarı İletken", "Veri Merkezi", "Yapay Zekâ", "Kuantum", "Otomasyon ve Robotik"],
    fundingAmount: "Çağrı bazında milyar dolar ölçekli toplam destek bütçeleri ve proje bazlı teşvikler",
    fundingType: "Proje bazlı teşvik, finansman, pazar geliştirme ve yatırım yeri desteği",
    supportRate: "Projenin stratejik değeri ve yatırım ölçeğine göre özel paket",
    duration: "Yatırım projesine göre",
    summary:
      "Elektrikli araç, batarya, çip, rüzgâr, Ar-Ge merkezi, veri merkezi, yapay zekâ, kuantum, endüstriyel robot ve yenilikçi savunma teknolojilerindeki büyük yatırımları kapsar.",
    objectives: [
      "Türkiye’de yüksek teknoloji üretim kapasitesi oluşturmak",
      "Kritik ürün ve teknoloji yatırımlarını yerlileştirmek",
      "Küresel ölçekte rekabetçi üretim ve Ar-Ge merkezleri kurmak",
    ],
    eligibleCosts: [
      "Çağrı koşullarını sağlayan yüksek teknoloji üretim yatırımları",
      "Ar-Ge merkezi, üretim tesisi ve kritik altyapı yatırımları",
      "Proje bazlı teşvik paketinde uygun görülen harcamalar",
    ],
    application: "HIT-30 çağrılar sayfasındaki aktif konu üzerinden veya kapsam dâhilindeki diğer yüksek teknoloji konuları için Bakanlığa başvurulur.",
    sourceUrl: "https://hit30.sanayi.gov.tr/cagrilar",
    sourceLabel: "Resmî Sanayi ve Teknoloji Bakanlığı HIT-30 çağrılar sayfası",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["HIT-30", "Yüksek Teknoloji", "Savunma", "Yatırım"],
    featured: true,
    notice: "Resmî sayfa, ilanlı aktif çağrılara ek olarak HIT-30 kapsamındaki diğer yüksek teknoloji konularında da başvuru alınabildiğini belirtiyor.",
  },
  {
    id: "ssb-saga-active",
    scope: "national",
    code: "SSB · SAGA",
    title: "SSB Ar-Ge Geniş Alan (SAGA) Çağrıları",
    institution: "T.C. Cumhurbaşkanlığı Savunma Sanayii Başkanlığı",
    institutionShort: "SSB",
    status: "open",
    openDate: "2026-01-01T00:00:00+03:00",
    applicationType: "continuous",
    applicants: "Savunma teknolojilerinde yetkin firma, kurum ve kuruluşlar",
    companyScale: ["KOBİ", "Büyük Ölçek", "Üniversite / Araştırma"],
    themes: ["Savunma Ar-Ge", "Dijital Dönüşüm", "Yapay Zekâ", "Deep Tech"],
    sectors: ["Savunma ve Güvenlik", "Havacılık ve Uzay", "Elektronik", "Dijital Teknolojiler", "Malzeme"],
    fundingAmount: "Seçilen aktif SAGA başlığının koşullarına göre",
    fundingType: "Ar-Ge proje çağrısı ve sözleşme bazlı destek",
    supportRate: "Aktif çağrı ve değerlendirme sonucuna göre",
    duration: "Proje önerisine ve çağrı koşullarına göre",
    summary:
      "SSB Ar-Ge Portalında listelenen aktif geniş alan başlıklarına firma ve kuruluşların özgün savunma teknolojisi proje önerileri sunmasını sağlar.",
    objectives: [
      "Savunma ve güvenlik alanında kritik teknoloji kazanımı sağlamak",
      "Sanayi, üniversite ve araştırma kuruluşlarının yetkinliklerini projeye dönüştürmek",
      "Yapay zekâ, elektronik, malzeme ve benzeri alanlarda yenilikçi çözümler geliştirmek",
    ],
    eligibleCosts: [
      "Aktif SAGA çağrısında uygun görülen Ar-Ge faaliyetleri",
      "Personel, prototip, test ve doğrulama giderleri",
      "Çağrı sözleşmesinde tanımlanan proje maliyetleri",
    ],
    application: "SSB Ar-Ge ve Teknoloji Yönetimi Portalındaki “SAGA Başvurusu” ekranından aktif çağrı seçilerek çevrimiçi proje önerisi sunulur.",
    sourceUrl: "https://arge.ssb.gov.tr/",
    sourceLabel: "Resmî SSB Ar-Ge ve Teknoloji Yönetimi Portalı",
    verifiedAt: "2026-07-26T15:00:00+03:00",
    tags: ["SSB", "SAGA", "Savunma", "Ar-Ge"],
    featured: true,
    notice: "Aktif SAGA konu başlıkları başvuru ekranındaki açılır listede gösterilir; başvuru öncesinde güncel başlığın portalda seçilebilir olduğu kontrol edilmelidir.",
  },
  {
    id: "tubitak-1707-2026-2",
    scope: "national",
    code: "1707 · 2026/2",
    title: "Siparişe Dayalı Ar-Ge Projeleri için KOBİ Destekleme",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK",
    status: "archived",
    openDate: "2026-05-04T00:00:00+03:00",
    deadline: "2026-07-17T23:59:00+03:00",
    applicants: "Müşteri kuruluş ile Türkiye’de yerleşik KOBİ tedarikçi kuruluşun ortak başvurusu",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    fundingAmount: "Çağrı dokümanındaki üst limitlere göre",
    fundingType: "TÜBİTAK ve müşteri kuruluş eş finansmanı",
    supportRate: "Çağrı dokümanına göre",
    duration: "Çağrı dokümanına göre",
    summary:
      "Müşteri kuruluşun ihtiyacını karşılayan ticarileşebilir bir ürün veya sürecin KOBİ tedarikçi tarafından Ar-Ge yoluyla geliştirilmesini destekler.",
    objectives: ["Sipariş odaklı Ar-Ge iş birlikleri kurmak", "Ticarileşme riskini paylaşmak", "KOBİ’lerin müşterisi hazır ürün geliştirmesini sağlamak"],
    eligibleCosts: ["Personel", "Alet ve teçhizat", "Malzeme ve hizmet alımları"],
    application: "Başvurular kapanmıştır. Yeni dönem takvimi resmî sayfadan izlenmelidir.",
    sourceUrl:
      "https://tubitak.gov.tr/tr/destekler/destek/sanayi/ulusal-destek-programlari/cagri-1707-siparise-dayali-ar-ge-projeleri-icin-kobi-destekleme-2026-2-cagrisi-acildi",
    sourceLabel: "Resmî TÜBİTAK çağrı sayfası",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Sipariş Ar-Ge", "KOBİ", "İş Birliği"],
    themes: ["Ar-Ge ve Yenilik", "Tedarik Zinciri", "Ürün Geliştirme"],
    sectors: ["İmalat", "Sektörler Arası"],
  },
  {
    id: "tubitak-1832-2026-1",
    scope: "national",
    code: "1832 · 2026/1",
    title: "Sanayide Yeşil Dönüşüm Çağrısı",
    institution: "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    institutionShort: "TÜBİTAK",
    status: "archived",
    openDate: "2026-04-01T00:00:00+03:00",
    deadline: "2026-06-09T23:59:00+03:00",
    applicants: "Yeşil teknoloji, ürün veya süreç geliştiren Türkiye’de yerleşik sermaye şirketleri",
    companyScale: ["KOBİ", "Büyük Ölçek"],
    fundingAmount: "Kuruluş ölçeğine ve program limitlerine göre",
    fundingType: "Geri ödemeli destek",
    supportRate: "Çağrı dokümanına göre",
    duration: "Çağrı dokümanına göre",
    summary:
      "Düşük karbonlu üretim, döngüsel ekonomi, temiz enerji, sürdürülebilir tarım ve ulaşım alanlarında THS 3–9 aralığındaki yeşil dönüşüm projelerini destekler.",
    objectives: ["Sanayinin yeşil dönüşümünü hızlandırmak", "Kaynak ve enerji verimliliğini artırmak", "Düşük karbonlu teknolojileri ölçeklemek"],
    eligibleCosts: ["Ar-Ge personeli", "Makine ve ekipman", "Pilot uygulama, malzeme ve hizmet alımları"],
    application: "Başvurular kapanmıştır. Yeni dönem çağrıları TÜBİTAK sayfasından izlenmelidir.",
    sourceUrl: "https://tubitak.gov.tr/tr/duyuru/1832-sanayide-yesil-donusum-2026-1-cagrisi-basvuruya-acildi",
    sourceLabel: "Resmî TÜBİTAK duyurusu",
    verifiedAt: "2026-07-24T12:00:00+03:00",
    tags: ["Yeşil Dönüşüm", "Döngüsel Ekonomi", "Sanayi"],
    themes: ["Yeşil Dönüşüm", "Döngüsel Ekonomi", "Enerji Verimliliği", "Kaynak Verimliliği"],
    sectors: ["İmalat", "Enerji", "Tarım ve Gıda", "Otomotiv ve Mobilite"],
  },
];
